#!/usr/bin/env python

Import("env")

env.Append(CPPPATH=["#modules/aurora_core/include"])

env.add_source_files(env.modules_sources, "*.cpp")
env.add_source_files(env.modules_sources, "src/*.cpp")
env.add_source_files(env.modules_sources, "src/events/*.cpp")
